from utils import run_cmd, enter, enter_n, space, enterF4, capture_output
from config import get_googlesheet_url
from sheets import *

def get_all(session, domain_name, qad_version, menu_number, function_index):
    '''
    This function generates a report with all the data from the 61.3.16 *Rep Contenedor Interno (Ex9.2.2) menu.
    Then gets the file generated by the report and updates Google Sheet with the new data.
    '''
    s = session
    tmp_localpath = "/tmp/cont_int.csv"
    googlesheet_url = get_googlesheet_url(qad_version, menu_number, function_index)
    if not googlesheet_url:
        raise ValueError(f"Google Sheet URL not found for {qad_version}, menu {menu_number}, function {function_index}")

    # Get path to cont_int.csv file
    run_cmd(s, enter_n(20))
    run_cmd(s, space(), wait_for="Se creo", timeout=400)
    csv_path_qad = capture_output(s, "archivo:", "cont_int.csv", "cont_int.csv")
    print("El url capturado es: ", csv_path_qad)

    # Go back to the CLI
    run_cmd(s, enterF4())
    run_cmd(s, enterF4())
    run_cmd(s, enterF4())
    run_cmd(s, 'Y' + enter())
    run_cmd(s, 'Q' + enter(), wait_for="Selection:")

    # Go the the root directory
    run_cmd(s, 'cd ..' + enter())
    run_cmd(s, 'cd ..' + enter())

    # Get .csv and overwrite the Google Sheet with the new data
    transfer_csv(s, csv_path_qad, tmp_localpath)
    insert_csv_to_googlesheet(tmp_localpath, googlesheet_url, sheet_name=domain_name)

menu_functions = {
    "Extraer Todos": get_all,
}