from utils import run_cmd, enter, enter_n, space, enterF4, capture_output
from config import get_googlesheet_url
from qad_ssh import get_ssh_session
from sheets import *

def get_all(session, domain_name, qad_version, menu_number, function_index):
    '''
    This function generates a report with all the data from the 61.3.16 *Rep Contenedor Interno (Ex9.2.2) menu.
    Then gets the file generated by the report and updates Google Sheet with the new data.
    '''

    if domain_name != 'SURFRUSD':
        print(f"Skipping execution for domain {domain_name}. This function only runs for SURFRUT.")
        return
    
    s = session
    tmp_localpath = "/tmp/cont_int.csv"
    googlesheet_url = get_googlesheet_url(qad_version, menu_number, function_index)
    if not googlesheet_url:
        raise ValueError(f"Google Sheet URL not found for {qad_version}, menu {menu_number}, function {function_index}")

    # Generate report then close session
    run_cmd(s, enter_n(20))
    run_cmd(s, space())
    run_cmd(s, enterF4())
    session.close()

    # Get .csv and overwrite the Google Sheet with the new data
    csv_path_qad = '/home/corellan/cont_int.csv' 
    s = get_ssh_session(qad_version)
    transfer_csv(s, csv_path_qad, tmp_localpath)
    insert_csv_to_googlesheet(tmp_localpath, googlesheet_url, sheet_name=domain_name)

menu_functions = {
    "Extraer Todos": get_all,
}