from utils import run_cmd, enter, enter_n, space, enterF4, capture_output
from sheets import *

def get_all(session, domain_name):
    '''
    This function generates a report with all the data from the 16.3.23 *Rep Costos Req vs Real menu.
    Then gets the file generated by the report and updates Google Sheet with the new data.
    '''
    s = session
    googlesheet = "https://docs.google.com/spreadsheets/d/1HZ3MoJb1c0KBP2mMyT7XCriLA9U-0gnisJLTEVsis9w/edit?usp=sharing"
    tmp_localpath = "/tmp/cost_req_vs_real.csv"

    # Get path to cont_int.csv file
    run_cmd(s, enter_n(9))
    run_cmd(s, "cost_req_vs_real" + enter())
    run_cmd(s, enter())
    csv_path = '/qond/apps/surfrut/transf_arch/cost_req_vs_real.csv' 
    print("El url capturado es: ", csv_path)

    # Go back to the CLI
    run_cmd(s, enterF4(), wait_for="F4 to exit.")
    run_cmd(s, enterF4())
    run_cmd(s, enterF4())
    run_cmd(s, enterF4())
    run_cmd(s, 'Y' + enter())
    run_cmd(s, 'Q' + enter(), wait_for="Selection:")

    # Go the the root directory
    run_cmd(s, 'cd ..' + enter())
    run_cmd(s, 'cd ..' + enter())

    # Get .csv and overwrite the Google Sheet with the new data
    transfer_csv(s, csv_path, tmp_localpath)
    insert_csv_to_googlesheet(tmp_localpath, googlesheet, sheet_name=domain_name, debug=True)

menu_functions = {
    "Extraer Todos": get_all,
}