from utils import run_cmd, enter, enter_n, space, enterF4, capture_output
from sheets import overwrite_csv_into_sheet

def get_all(session):
    '''
    This function generates a report with all the data from the 61.3.16 *Rep Contenedor Interno (Ex9.2.2) menu.
    Then gets the file generated by the report and updates Google Sheet with the new data.
    '''
    s = session
    googlesheet = "https://docs.google.com/spreadsheets/d/1cjQmvLxlmPas0LlASsmRhV14CQ76baw18aLqDYHzO2s/edit?usp=sharing"

    # Get path to cont_int.csv file
    run_cmd(s, enter_n(20))
    run_cmd(s, space())
    csv_path = capture_output(s, "archivo:", "cont_int.csv", "cont_int.csv")
    print("El url capturado es: ", csv_path)

    # Go back to the CLI
    run_cmd(s, space())
    run_cmd(s, enterF4())
    run_cmd(s, enterF4())
    run_cmd(s, enterF4())
    run_cmd(s, 'Y' + enter())
    run_cmd(s, 'Q' + enter(), wait_for="Selection:")

    # Go the the root directory
    run_cmd(s, 'cd ..' + enter())
    run_cmd(s, 'cd ..' + enter())

    # Get .csv and overwrite the Google Sheet with the new data
    overwrite_csv_into_sheet(s, csv_path, googlesheet, "/tmp")

menu_functions = {
    "Extraer Todos": get_all,
}