from utils import run_cmd, enter, enter_n, space, enterF4, capture_output
from config import get_googlesheet_url
from sheets import *

def get_all(session, domain_name, qad_version, menu_number, function_index):
    '''
    This function generates a report with all the data from the 16.3.23 *Rep Costos Req vs Real menu.
    Then gets the file generated by the report and updates Google Sheet with the new data.
    '''
    s = session
    tmp_localpath = "/tmp/cost_req_vs_real.csv"
    googlesheet_url = get_googlesheet_url(qad_version, menu_number, function_index)
    if not googlesheet_url:
        raise ValueError(f"Google Sheet URL not found for {qad_version}, menu {menu_number}, function {function_index}")

    # Get path to cont_int.csv file
    run_cmd(s, enter_n(9))
    run_cmd(s, "cost_req_vs_real" + enter())
    run_cmd(s, enter())
    csv_path = '/qond/apps/surfrut/transf_arch/cost_req_vs_real.csv' 
    print("El url capturado es: ", csv_path)

    # Go back to the CLI
    if qad_version == 'new03':
        run_cmd(s, enterF4(), wait_for="F4 to exit.")
    else:
        run_cmd(s, enterF4())
    run_cmd(s, enterF4())
    run_cmd(s, enterF4())
    run_cmd(s, enterF4())
    run_cmd(s, 'Y' + enter())
    run_cmd(s, 'Q' + enter(), wait_for="Selection:")

    # Go the the root directory
    run_cmd(s, 'cd ..' + enter())
    run_cmd(s, 'cd ..' + enter())

    # Get .csv and overwrite the Google Sheet with the new data
    transfer_csv(s, csv_path, tmp_localpath)
    insert_csv_to_googlesheet(tmp_localpath, googlesheet_url, sheet_name=domain_name)

menu_functions = {
    "Extraer Todos": get_all,
}