version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /path/on/lightsail:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json

volumes:
  data: