version: '3'

services:
  qad-automate:
    build: .
    image: qad-automate:${TAG:-latest}
    volumes:
      - .:/app
      - ./config/programmed_executions.yaml:/app/config/programmed_executions.yaml
    env_file:
      - .env
    environment:
      - TZ=America/Santiago