# Configuration for Google Sheet URLs

new02:
  "61.3.16":
    1: "11Iq5vnyIuq7HwfRsIsVlsDglwH06Huh5OuZ-vNE7-AY"
  "16.3.23":
    1: "1OlbWz_VqqQ7-Q739j8OlcFM-i5k72sukUvGLapJIJhU"

new03:
  "61.3.16":
    1: "1cjQmvLxlmPas0LlASsmRhV14CQ76baw18aLqDYHzO2s"
  "16.3.23":
    1: "1HZ3MoJb1c0KBP2mMyT7XCriLA9U-0gnisJLTEVsis9w"