executions:

# PROD
  - name: "16.3.23 *Rep Costos Req vs Real"
    command: "python /app/src/main.py new03 16.3.23 1"
    schedule: "30 23 * * 0"

  - name: "9.2.2 *Rep Container Interno"
    command: "python /app/src/main.py old01 9.2.2 1 SURFRUSD"
    schedule: "45 23 * * 0"

  - name: "61.3.16 *Rep Contenedor Interno (Ex9.2.2)"
    command: "python /app/src/main.py new03 61.3.16 1"
    schedule: "40 23 * * 0"
  
# TEST 
  - name: "TEST 16.3.23 *Rep Costos Req vs Real"
    command: "python /app/src/main.py new02 16.3.23 1"
    schedule: "*/25 * * * *"

  - name: "TEST 61.3.16 *Rep Contenedor Interno (Ex9.2.2)"
    command: "python /app/src/main.py new02 61.3.16 1"
    schedule: "*/15 * * * *"
